# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ../../input/M2D_segment_single_data/test_bone.npy
  label_path: ../../input/M2D_segment_single_data/test_label.pkl
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 4
  num_point: 23
  num_person: 1
  graph: graph.m2d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0]
test_batch_size: 48
weights: ./runs/m2d_segment_single_bone-99-300.pt

work_dir: ./work_dir/m2d_segment_single/m2d_test_bone
model_saved_name: ./runs/m2d_segment_single/m2d_test_bone
save_score: True